### ISSUE TITLE
Install with composer.json

### ISSUE THREAD

**Issue by watilde** [eviweb/fuelphp-phpcs#3]
Hi.

Can I install this nice rule with composer? It become more userfull if it can.

e.g.
Currently I use this with `git submodule`, here is my case:

1. install rule
```
cd fuel/vendor
git submodule add -f git@github.com:eviweb/fuelphp-phpcs.git

```

2. composer script
```json
    "scripts": {
        "lint": [
            "phpcs --standard=fuel/vendor/fuelphp-phpcs/Standards/FuelPHP/ruleset.xml fuel/app"
        ]
    },
```

3. run
```
composer run lint
```

Thanks.

**Comment by eviweb** [comment]
Hi @watilde,

thanks for sharing, work is in progress.

Eric

**Comment by eviweb** [comment]
Hi @watilde,

composer support was added in [v1.0.4](https://github.com/eviweb/fuelphp-phpcs/releases/tag/v1.0.4)

Using the code below should answer your needs:
```
  "scripts": {
        "lint": [
            "./fuel/vendor/bin/fuelphpcs fuel/app"
        ]
    },
```

Best regards

Eric

**Comment by watilde** [comment]
@eviweb Thanks for your super quick response! Merci bien :-)

**Comment by eviweb** [comment]
@watilde,

you're welcome ;-).
I hope you will profit of this improvement.
Great thanks for your contribution

Eric
